image::https://img.shields.io/github/downloads/SomeBoringNerd/waifuhax/total[total download]
image::https://img.shields.io/github/contributors-anon/SomeBoringNerd/waifuhax[contributors]

= WaifuHax

former private client, now public, free and open source

=== How to compile

open a terminal and use type `./gradlew build`

=== How to use

ClickGUI's default key is right shift, if it don't work use the command
`-clickgui set_key` and then press right shift

= Modules and their settings

=== Note
to change a setting, type in chat `-${module's name} ${parameter you want to change} ${new value}`

or you can use the clickgui.

To know what each setting do, type -${module's name}

= Credits

me for the code

google for the json stuff

Meteordev for their event system

cyyynthia for creating PronounDB and supporting Minecraft

Pr3roxDLC for showing me how to use @interfaces

Tex06 for the good "medicinal plants" that I smoked while working on this.

Nodus client for the general aesthetic, Earthhack for some ideas.

TaxMachine along with isma67 for support
