image::https://img.shields.io/github/contributors-anon/SomeBoringNerd/waifuhax[contributors]
'''
= WaifuHax

WaifuHax is a client base for Minecraft 1.19.4.

It was made for anarchy servers, this base contain :

>A save system

>A click GUI

>Custom main menu

>read the code and see for yourself

== How to compile
==== Windows
[cols="~,~"]
|===

| Step 1
| git clone it using github desktop or CLI

| step 2
| gradlew build
|===

==== MacOS / Linux
[cols="~,~"]
|===

| Step 1
| git clone https://github.com/SomeBoringNerd/WaifuHax

| step 2
| ./gradlew build
|===

=== How to use

ClickGUI's default key is right shift, if it don't work use the command
`-set clickgui key` and then press right shift

== Modules and their settings

=== Note
to change a setting, type in chat `-${module's name} ${parameter you want to change} ${new value}`

or you can use the clickgui.

To know what each setting do, type -${module's name}

== Credits

[cols="~,~"]
|===

| SomeBoringNerd
| Client base

| MeteorDev
| Orbit system, fast and easy event system

| Pr3roxDLC
| Some tips to improve WaifuHax
|===
